# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
	install-pip-deps:
		runs-on: ubuntu-latest
		steps:
			- uses: actions/checkout@v3.5.2
	 
			# - name: Install pip
				run: echo pip install -r requirements.txt
	deploy-to-dev:
		 runs-on: ubuntu-latest
		 steps:
         
	tests-on-dev:
	deploy-to-staging:
	tests-on-staging:
	deploy-to-preprod:
	tests-on-preprod:
	deploy-to-prod:
	Tests-on-prod:
	Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
